valentin_films_manager_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ValentinFilmsManagerBundle:Default:index }

valentin_films_manager_index:
    path:      /{page}
    defaults:  { _controller: ValentinFilmsManagerBundle:Manager:index, page: 1 }
    requirements:
        page:  \d*

valentin_films_manager_addUser:
    path:      /addUser
    defaults:  { _controller: ValentinFilmsManagerBundle:Manager:addUser }

valentin_films_manager_addFilm:
    path:      /addFilm
    defaults:  { _controller: ValentinFilmsManagerBundle:Manager:addFilm }

valentin_films_manager_removeFilm:
    path:      /removeFilm/{id}
    defaults:  { _controller: ValentinFilmsManagerBundle:Manager:removeFilm }
    requirements:
        id:  \d+